title: Dan Hachuel 
logo: "/Index.html/Foto_Github.png?raw=true"

description: Bookmark this to keep an eye on my project updates!
Brazilian and Spanish guy
<a href="https://www.linkedin.com/in/dan-hachuel/">My LinkedIn</a> 

Degrees
• High School Tech in Computering;
• B.A. in Software Engineering;
• B.A. in Business Administration;
• MBA in Data Engineering;
• MsC Computational Inteligence, in course

<br><br>
  
Certifications
• Scrum Foundation Professional - SFPC™
• OKR Foundations - OKRE™
• Fortinet - NSE3 Network Security Expert - Associate
• CISCO Introduction to Cybersecurity
• CISCO Cybersecurity
• CISCO Packet Tracer
• Gitlab Associate
• Green Belt Lean Six Sigma

 <br><br>
  
theme: jekyll-theme-minimal 
google_analytics: G-FRHQQBBLJR
